import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import AuthProvider from "@/app/components/auth-provider";
import JotaiProvider from "@/app/components/jotai-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={"bg-neutral-50"}>
        <AuthProvider>
          <JotaiProvider>{children}</JotaiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
